import "./globals.css";
import QueryProvider from "./QueryProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F1DFDF] dark:bg-[#5c5454] text-black dark:text-white">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
