import "./globals.css";
import QueryProvider from "./QueryProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
